- id: lucy_doorbell
  alias: Lucy's Doorbell TTS
  trigger:
  - entity_id: switch.10006abf86
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: tts.google_say
    entity_id: media_player.living_room_speaker
    data:
      message: It sounds like Lucy wants to go outside!
  - service: media_player.alexa_tts
    entity_id: media_player.bedroom
    data:
      message: It sounds like Lucy wants to go outside!
  - service: media_player.alexa_tts
    entity_id: media_player.basement
    data:
      message: It sounds like Lucy wants to go outside!
  - service: media_player.alexa_tts
    entity_id: media_player.spare_bedroom
    data:
      message: It sounds like Lucy wants to go outside!
      
- id: lucy_doorbell_sms
  alias: Lucy's Doorbell SMS
  trigger:
  - entity_id: switch.10006abf86
    from: 'off'
    platform: state
    to: 'on'
  action:
    service: notify.lucy_doorbell
    data:
      title: WOOF!
      message: Lucy is letting you know that she wants outside!

- id: emulated_hue_alexa
  alias: Alexa TTS via Emulated Hue
  trigger:
  - entity_id: light.alexa_virtual
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - service: alexa_media.update_last_called
  - delay: 00:00:01
  - data_template:
      entity_id: '{{ states.sensor.last_alexa.state }}'
      message:  >-
        {% if (states.light.alexa_virtual.attributes.brightness | int / 255 * 100 ) | round  == 1 %}
          The current pool temperature is {{states('sensor.converted_pool_temp')|replace('.', ' point ') }} degrees
        {% elif (states.light.alexa_virtual.attributes.brightness | int / 255 * 100 ) | round  == 2 %}
          The current download speed is {{states('sensor.speedtest_download')|replace('.', ' point ') }} mega bits per second
        {% elif (states.light.alexa_virtual.attributes.brightness | int / 255 * 100 ) | round  == 3 %}
          Turning on the night lights
        {% else %}
         {{ states('light.alexa_virtual.attributes.brightness') }}
        {% endif %}
    service: media_player.alexa_tts
  - service: homeassistant.turn_off
    entity_id: light.alexa_virtual
    
- id: chelsea_home
  alias: Chelsea is home
  trigger:
  - entity_id: person.chelsea_crowe
    from: not_home
    platform: state
    to: home
  condition:
  - after: 08:00:00
    before: '22:00:00'
    condition: time
  action:
  - data:
      message: It looks like Chelsea is home now
    entity_id: media_player.living_room_speaker
    service: tts.google_say
  - data:
      message: It looks like Chelsea is home now
    entity_id: media_player.bedroom
    service: media_player.alexa_tts
  - data:
      message: It looks like Chelsea is home now
    entity_id: media_player.basement
    service: media_player.alexa_tts
  - data:
      message: It looks like Chelsea is home now
    entity_id: media_player.spare_bedroom
    service: media_player.alexa_tts
    
- id: patrick_home
  alias: Patrick is home
  trigger:
  - entity_id: person.patrick_mcenaney
    from: not_home
    platform: state
    to: home
  condition:
  - after: 08:00:00
    before: '22:00:00'
    condition: time
  action:
  - data:
      message: It looks like Patrick is home now
    entity_id: media_player.living_room_speaker
    service: tts.google_say
  - data:
      message: It looks like Patrick is home now
    entity_id: media_player.bedroom
    service: media_player.alexa_tts
  - data:
      message: It looks like Patrick is home now
    entity_id: media_player.basement
    service: media_player.alexa_tts
  - data:
      message: It looks like Patrick is home now
    entity_id: media_player.spare_bedroom
    service: media_player.alexa_tts
    
- id: chelsea_leaving_work
  alias: Chelsea leaving work
  trigger:
  - platform: zone
    event: leave
    zone: zone.trading_post
    entity_id: person.chelsea_crowe
  action:
  - service: media_player.alexa_tts
    entity_id: media_player.bedroom
    data:
      message: It looks like Chelsea is finished work now
  - service: media_player.alexa_tts
    entity_id: media_player.basement
    data:
      message: It looks like Chelsea is finished work now
  - service: media_player.alexa_tts
    entity_id: media_player.spare_bedroom
    data:
      message: It looks like Chelsea is finished work now

- id: night_lights_on
  alias: Night Lights Switch On
  trigger:
  - entity_id: switch.night_light_switch
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: light.turn_on
    entity_id:
    - light.01200315600194696f39
    - light.01200823ecfabc8157e3
    - light.01200823ecfabc815d16 
    data:
      brightness: 13
      color_name: cyan
  - service: homeassistant.turn_off
    entity_id:
    - switch.1000277820      
    - switch.1000280b79   
    
- id: night_lights_off
  alias: Night Lights Switch Off
  trigger:
  - platform: state
    entity_id: switch.night_light_switch
    from: 'on'
    to: 'off'
  action:
  - service: light.turn_off
    entity_id:
    - light.01200315600194696f39
    - light.01200823ecfabc8157e3
    - light.01200823ecfabc815d16
  - service: homeassistant.turn_off
    entity_id:
    - switch.1000277820      
    - switch.1000280b79      
    
- id: bright_lights
  alias: Bright Bedroom Lights
  trigger:
  - platform: state
    entity_id: group.bedroom
    from: 'off'
    to: 'on'
  action:
  - service: light.turn_on
    entity_id:
    - light.01200315600194696f39
    - light.01200823ecfabc8157e3
    - light.01200823ecfabc815d16 
    data:
      brightness: 255
      color_name: white
