###################################################
#     Home Assistant Main Configuration File      #
###################################################

homeassistant:
  name: Home
  latitude: !secret location_lat
  longitude: !secret location_long
  elevation: !secret location_elev
  unit_system: metric
  time_zone: !secret location_tz
  customize: !include customize.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
  
config:  

introduction:

discovery:

conversation:

history:

logbook:

map:

sun:

system_health:

cloud:

updater:

frontend:
  themes: !include themes.yaml
  
http:
    api_password: !secret http_password
    
tts:
  - platform: google
  
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.0.131:3218
    
weather:
  - platform: darksky
    mode: daily
    api_key: !secret darksky_key
    
    
### Devices ###    
    
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_key
  
camera:
    platform: ffmpeg
    input: rtsp://192.168.0.135:554/onvif1
    name: Front Door Camera

sonoff:
    username: !secret sonoff_user
    password: !secret sonoff_pass
    scan_interval: 10
    grace_period: 600
    api_region: 'us'
    
tuya:
  username: !secret tuya_user
  password: !secret tuya_pass
  country_code: 1
  platform: smart_life
  
light:
  - platform: flux_led
    automatic_add: true
    
remote:
  - platform: harmony
    name: Livingroom Hub
    host: 192.168.0.111
  - platform: harmony
    name: Bedroom Hub
    host: 192.168.0.112
  - platform: harmony
    name: Basement Hub
    host: 192.168.0.122

media_player:
  - platform: emby
    host: 192.168.0.124
    api_key: !secret emby_key
    auto_hide: true
  - platform: alexa
    email: !secret alexa_email
    password: !secret alexa_pass
    url: amazon.ca
