# Weather prediction
- platform: darksky
  api_key: !secret darksky_key
  forecast:
    - 1
  monitored_conditions:
    - summary
    - icon
    - temperature
    - wind_bearing
    - apparent_temperature
    - temperature_min
    - temperature_max
    - humidity
    - precip_probability
    - precip_intensity
    - precip_type
    - wind_speed
    - wind_bearing
    - pressure