background: center / cover no-repeat url("/local/bg/background6.jpg") fixed
resources:
  - type: module
    url: /local/mini-media-player-bundle.js?v=1.0.1
  - type: module
    url: >-
      https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/weather-card.min.js
  - type: module
    url: /local/custom-ui/compact-custom-header/compact-custom-header.js?v=0.0.1
title: Dashboard
views:
  - badges: []
    cards:
      - clock_format: '12'
        menu: overflow
        notifications: hide
        options: clock
        type: 'custom:compact-custom-header'
        voice: overflow
      - cards:
          - entity: climate.living_room
            type: thermostat
          - entity: camera.front_door_camera
            type: picture-entity
        type: vertical-stack
      - cards:
          - artwork: cover
            entity: media_player.living_room_speaker
            hide:
              icon: true
              panel: false
              power_state: true
              source: true
              volume: false
            source: icon
            type: 'custom:mini-media-player'
          - entity: media_player.bedroom
            hide:
              icon: true
            type: 'custom:mini-media-player'
          - entity: media_player.spare_bedroom
            hide:
              icon: true
            type: 'custom:mini-media-player'
          - entity: media_player.basement
            hide:
              icon: true
            type: 'custom:mini-media-player'
          - artwork: cover
            auto_hide: true
            entity: media_player.emby_emby_theater_hellspawn
            hide:
              icon: true
              panel: false
              power_state: true
              source: true
              volume: true
            source: icon
            type: 'custom:mini-media-player'
          - artwork: cover
            auto_hide: true
            entity: media_player.emby_emby_theater_bedroom_mini_pc
            hide:
              icon: true
              panel: false
              power_state: true
              source: true
              volume: true
            source: icon
            type: 'custom:mini-media-player'
          - artwork: cover
            auto_hide: true
            entity: media_player.emby_androidtv_t95zplus
            hide:
              icon: true
              panel: false
              power_state: true
              source: true
              volume: true
            source: icon
            type: 'custom:mini-media-player'
        type: vertical-stack
      - entity: weather.dark_sky
        type: 'custom:weather-card'
      - columns: 2
        entities:
          - entity: group.lights
            icon: 'mdi:lightbulb'
            tap_action:
              action: toggle
          - entity: group.all_remotes
            icon: 'mdi:television-classic'
            name: All TV's
            tap_action:
              action: toggle
        type: glance
    icon: 'mdi:home'
    panel: false
    path: default_view
    title: Home
  - badges: []
    cards:
      - entity: camera.front_door_camera
        type: picture-entity
    icon: 'mdi:cctv'
    title: Security Camera
  - cards:
      - cards:
          - entities:
              - entity: switch.01200209ecfabc03a885
                icon: 'mdi:fish'
                tap_action:
                  action: toggle
            show_name: true
            show_state: false
            type: glance
          - entities:
              - entity: light.01200315600194696f39
                icon: 'mdi:lightbulb'
                tap_action:
                  action: toggle
            show_name: true
            show_state: false
            type: glance
          - entities:
              - entity: light.01200823ecfabc8157e3
                icon: 'mdi:lightbulb'
                tap_action:
                  action: toggle
            show_name: true
            show_state: false
            type: glance
        type: horizontal-stack
      - cards:
          - entities:
              - entity: light.01200823ecfabc815d16
                icon: 'mdi:lightbulb'
                tap_action:
                  action: toggle
            show_name: true
            show_state: false
            type: glance
          - entities:
              - entity: switch.sonoff_1000277820
                icon: 'mdi:lightbulb'
                tap_action:
                  action: toggle
            show_name: true
            show_state: false
            type: glance
          - entities:
              - entity: switch.sonoff_1000280b79
                icon: 'mdi:lightbulb'
                tap_action:
                  action: toggle
            show_name: true
            show_state: false
            type: glance
        type: horizontal-stack
      - entity: group.bedroom
        hold_action:
          action: none
        icon: 'mdi:lightbulb'
        name: All Lights
        tap_action:
          action: toggle
        type: entity-button
      - cards:
          - entity: media_player.emby_emby_theater_bedroom_mini_pc
            hide:
              icon: true
              panel: false
              power_state: true
              source: true
              volume: true
            source: icon
            type: 'custom:mini-media-player'
          - entity: media_player.bedroom
            hide:
              icon: true
            type: 'custom:mini-media-player'
        type: vertical-stack
      - entity: remote.bedroom_hub
        icon: 'mdi:television-classic'
        name: Watch TV
        tap_action:
          action: call-service
          service: remote.turn_on
          service_data:
            activity: Watch TV
            entity_id: remote.bedroom_hub
        type: entity-button
      - entity: remote.bedroom_hub
        icon: 'mdi:desktop-classic'
        name: Use the Computer
        tap_action:
          action: call-service
          service: remote.turn_on
          service_data:
            activity: Bedroom Computer
            entity_id: remote.bedroom_hub
        type: entity-button
      - entity: remote.bedroom_hub
        icon: 'mdi:power'
        name: Turn off bedroom tv
        tap_action:
          action: call-service
          service: remote.turn_off
          service_data:
            entity_id: remote.bedroom_hub
        type: entity-button
    icon: 'mdi:hotel'
    title: Bedroom
    type: vertical-stack
  - badges: []
    cards:
      - cards:
          - entities:
              - entity: switch.sonoff_1000280d3c
                icon: 'mdi:lightbulb'
                tap_action:
                  action: toggle
            show_name: true
            show_state: false
            type: glance
        type: horizontal-stack
      - entity: media_player.spare_bedroom
        hide:
          icon: true
        type: 'custom:mini-media-player'
    icon: 'mdi:bed-empty'
    title: Spare Bedroom
  - badges: []
    cards:
      - cards:
          - entities:
              - entity: light.6001949696af_192_168_0_120
                icon: 'mdi:lightbulb'
                tap_action:
                  action: toggle
            show_name: true
            show_state: false
            type: glance
          - entities:
              - entity: switch.01200446600194676548
                icon: 'mdi:lightbulb'
                tap_action:
                  action: toggle
            show_name: true
            show_state: false
            type: glance
        type: horizontal-stack
      - cards:
          - entities:
              - entity: switch.012004466001946ebdcc
                icon: 'mdi:lightbulb'
                tap_action:
                  action: toggle
            show_name: true
            show_state: false
            type: glance
          - entities:
              - entity: switch.sonoff_10001402d0
                icon: 'mdi:lightbulb'
                tap_action:
                  action: toggle
            show_name: true
            show_state: false
            type: glance
        type: horizontal-stack
      - entity: group.livingroom
        hold_action:
          action: none
        icon: 'mdi:lightbulb'
        name: All Lights
        tap_action:
          action: toggle
        type: entity-button
      - cards:
          - entity: media_player.emby_emby_theater_hellspawn
            hide:
              icon: true
              panel: false
              power_state: true
              source: true
              volume: true
            source: icon
            type: 'custom:mini-media-player'
          - artwork: cover
            entity: media_player.living_room_speaker
            hide:
              icon: true
              panel: false
              power_state: true
              source: true
              volume: false
            source: icon
            type: 'custom:mini-media-player'
        type: vertical-stack
      - entity: remote.livingroom_hub
        icon: 'mdi:television-classic'
        name: Watch TV
        tap_action:
          action: call-service
          service: remote.turn_on
          service_data:
            activity: Watch TV
            entity_id: remote.livingroom_hub
        type: entity-button
      - entity: remote.livingroom_hub
        icon: 'mdi:desktop-classic'
        name: Use the Computer
        tap_action:
          action: call-service
          service: remote.turn_on
          service_data:
            activity: The Computer
            entity_id: remote.livingroom_hub
        type: entity-button
      - entity: remote.livingroom_hub
        icon: 'mdi:emby'
        name: Start Emby Theater
        tap_action:
          action: call-service
          service: remote.turn_on
          service_data:
            activity: Emby Theater
            entity_id: remote.livingroom_hub
        type: entity-button
      - entity: remote.livingroom_hub
        icon: 'mdi:power'
        name: Turn off livingroom tv
        tap_action:
          action: call-service
          service: remote.turn_off
          service_data:
            entity_id: remote.livingroom_hub
        type: entity-button
    icon: 'mdi:sofa'
    title: Livingroom
    type: vertical-stack
  - badges: []
    cards:
      - cards:
          - entities:
              - entity: switch.sonoff_1000280c06
                icon: 'mdi:lightbulb'
                tap_action:
                  action: toggle
            show_name: true
            show_state: false
            type: glance
          - entities:
              - entity: switch.sonoff_1000280a7e
                icon: 'mdi:lightbulb'
                tap_action:
                  action: toggle
            show_name: true
            show_state: false
            type: glance
          - entities:
              - entity: switch.42514300b4e62d1e2379
                icon: 'mdi:lightbulb'
                tap_action:
                  action: toggle
            show_name: true
            show_state: false
            type: glance
        type: horizontal-stack
      - entity: media_player.emby_androidtv_t95zplus
        hide:
          icon: true
          panel: false
          power_state: true
          source: true
          volume: true
        source: icon
        type: 'custom:mini-media-player'
      - entity: group.basement
        hold_action:
          action: none
        icon: 'mdi:lightbulb'
        name: All Lights
        tap_action:
          action: toggle
        type: entity-button
      - entity: media_player.basement
        hide:
          icon: true
        type: 'custom:mini-media-player'
      - cards:
          - entity: remote.basement_hub
            icon: 'mdi:theater'
            name: Turn On Theater
            tap_action:
              action: call-service
              service: remote.turn_on
              service_data:
                activity: Projector
                entity_id: remote.basement_hub
            type: entity-button
          - entity: remote.basement_hub
            icon: 'mdi:power'
            name: Turn off Theater
            tap_action:
              action: call-service
              service: remote.turn_off
              service_data:
                entity_id: remote.basement_hub
            type: entity-button
        type: vertical-stack
    icon: 'mdi:theater'
    title: Basement
